# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Install dependencies
        run: |
          poetry run pip install -U --user pip setuptools
          poetry install
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
